; Inno Setup script for EcoTrack Hardware Bridge
; Builds: EcoTrackHardwareBridgeSetup.exe
;
; Build steps:
;   1. dotnet publish -c Release -r win-x64 --self-contained false
;   2. cd installer
;   3. iscc EcoTrackHardwareBridge.iss
;
; Notes:
;   - bridge.config.json is generated by this script (not copied from publish).
;   - Logs in C:\ProgramData\EcoTrack\Logs are intentionally left untouched on uninstall.

#define AppName "EcoTrack Hardware Bridge"
#define AppVersion "1.0.0"
#define AppPublisher "EcoTrack"
#define AppExeName "EcoTrack.HardwareBridge.exe"
#define PublishDir "..\bin\Release\net8.0-windows\win-x64\publish"

#define ConfigApiUrl "http://167.233.232.174"
#define ConfigApiKey "eco-track-bridge-test-key-2026"
#define ConfigWebSocketHost "0.0.0.0"
#define ConfigWebSocketPort "5001"

#define UninstallRegKey "Software\Microsoft\Windows\CurrentVersion\Uninstall\{7E4C2B1A-5D3F-4A9E-8C21-9F0B6E7A1C34}_is1"
#define UninstallRegKeyWow64 "Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{7E4C2B1A-5D3F-4A9E-8C21-9F0B6E7A1C34}_is1"

[Setup]
AppId={{7E4C2B1A-5D3F-4A9E-8C21-9F0B6E7A1C34}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
DefaultDirName={commonpf}\EcoTrack\HardwareBridge
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\{#AppExeName}
OutputDir=Output
OutputBaseFilename=EcoTrackHardwareBridgeSetup
Compression=lzma2
SolidCompression=yes
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "bridge.config.json"

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{commonstartup}\{#AppName}"; Filename: "{app}\{#AppExeName}"

[Run]
Filename: "{app}\{#AppExeName}"; Description: "Launch {#AppName}"; Flags: nowait postinstall skipifsilent

[Code]
var
  CheckpointPage: TInputQueryWizardPage;
  EnteredCheckpointId: Integer;
  SkipCheckpointPage: Boolean;

function GetUninstallInstallLocation(): String;
var
  Location: String;
begin
  Result := '';
  if RegQueryStringValue(HKLM, '{#UninstallRegKey}', 'InstallLocation', Location) then
    Result := Location
  else if RegQueryStringValue(HKLM, '{#UninstallRegKeyWow64}', 'InstallLocation', Location) then
    Result := Location;
end;

function TrimString(const Value: String): String;
begin
  Result := Value;
  while (Length(Result) > 0) and (Result[1] in [' ', #9, #13, #10]) do
    Delete(Result, 1, 1);
  while (Length(Result) > 0) and (Result[Length(Result)] in [' ', #9, #13, #10]) do
    Delete(Result, Length(Result), 1);
end;

function ExtractJsonString(const Json, Key: String): String;
var
  KeyToken, Tail: String;
  KeyPos, ValueStart, ValueEnd: Integer;
begin
  Result := '';
  KeyToken := '"' + Key + '":';
  KeyPos := Pos(KeyToken, Json);
  if KeyPos = 0 then
    Exit;

  Tail := Copy(Json, KeyPos + Length(KeyToken), MaxInt);
  ValueStart := 1;
  while (ValueStart <= Length(Tail)) and (Tail[ValueStart] in [' ', #9, #13, #10]) do
    Inc(ValueStart);

  if (ValueStart > Length(Tail)) or (Tail[ValueStart] <> '"') then
    Exit;

  Inc(ValueStart);
  ValueEnd := ValueStart;
  while (ValueEnd <= Length(Tail)) and (Tail[ValueEnd] <> '"') do
    Inc(ValueEnd);

  Result := TrimString(Copy(Tail, ValueStart, ValueEnd - ValueStart));
end;

function ExtractJsonInt(const Json, Key: String): Integer;
var
  KeyToken, Tail, Digits: String;
  KeyPos, ValueStart, I: Integer;
begin
  Result := -1;
  KeyToken := '"' + Key + '":';
  KeyPos := Pos(KeyToken, Json);
  if KeyPos = 0 then
    Exit;

  Tail := Copy(Json, KeyPos + Length(KeyToken), MaxInt);
  ValueStart := 1;
  while (ValueStart <= Length(Tail)) and (Tail[ValueStart] in [' ', #9, #13, #10]) do
    Inc(ValueStart);

  if (ValueStart > Length(Tail)) then
    Exit;

  if Copy(Tail, ValueStart, 4) = 'null' then
    Exit;

  Digits := '';
  I := ValueStart;
  while (I <= Length(Tail)) and (Tail[I] >= '0') and (Tail[I] <= '9') do
  begin
    Digits := Digits + Tail[I];
    Inc(I);
  end;

  if Digits <> '' then
    Result := StrToInt(Digits);
end;

function HasValidIdentity(CheckpointId: Integer; const BridgeId: String): Boolean;
begin
  Result := (CheckpointId >= 1) and (CheckpointId <= 999) and (TrimString(BridgeId) <> '');
end;

function FormatBridgeId(CheckpointId: Integer): String;
var
  IdText: String;
begin
  IdText := IntToStr(CheckpointId);
  if Length(IdText) < 2 then
    IdText := '0' + IdText;
  Result := 'checkpoint-' + IdText + '-bridge';
end;

function BuildBridgeConfigJson(CheckpointId: Integer; const BridgeId: String): String;
begin
  Result :=
    '{' + #13#10 +
    '  "ApiUrl": "{#ConfigApiUrl}",' + #13#10 +
    '  "ApiKey": "{#ConfigApiKey}",' + #13#10 +
    '  "BridgeId": "' + BridgeId + '",' + #13#10 +
    '  "CheckpointId": ' + IntToStr(CheckpointId) + ',' + #13#10 +
    '  "EnableCloudSync": true,' + #13#10 +
    '  "WebSocket": {' + #13#10 +
    '    "Host": "{#ConfigWebSocketHost}",' + #13#10 +
    '    "Port": {#ConfigWebSocketPort}' + #13#10 +
    '  }' + #13#10 +
    '}';
end;

function ReadExistingIdentity(const ConfigPath: String; var CheckpointId: Integer; var BridgeId: String): Boolean;
var
  JsonText: AnsiString;
begin
  Result := False;
  CheckpointId := -1;
  BridgeId := '';

  if not FileExists(ConfigPath) then
    Exit;

  if not LoadStringFromFile(ConfigPath, JsonText) then
    Exit;

  CheckpointId := ExtractJsonInt(JsonText, 'CheckpointId');
  BridgeId := ExtractJsonString(JsonText, 'BridgeId');
  Result := HasValidIdentity(CheckpointId, BridgeId);
end;

function TryParseCheckpointInput(const Value: String; var CheckpointId: Integer): Boolean;
var
  Trimmed: String;
  I: Integer;
begin
  Result := False;
  CheckpointId := -1;
  Trimmed := TrimString(Value);

  if Trimmed = '' then
    Exit;

  for I := 1 to Length(Trimmed) do
    if not ((Trimmed[I] >= '0') and (Trimmed[I] <= '9')) then
      Exit;

  CheckpointId := StrToIntDef(Trimmed, -1);
  Result := (CheckpointId >= 1) and (CheckpointId <= 999);
end;

procedure InitializeWizard();
var
  ExistingConfigPath: String;
  ExistingCheckpointId: Integer;
  ExistingBridgeId: String;
  InstallLocation: String;
begin
  EnteredCheckpointId := -1;
  SkipCheckpointPage := False;

  CheckpointPage := CreateInputQueryPage(
    wpSelectDir,
    'Checkpoint Configuration',
    'Enter the checkpoint ID for this bridge',
    'Specify the checkpoint where this bridge will operate.' + #13#10 +
    'Checkpoint ID must be a number from 1 to 999.');

  CheckpointPage.Add('Checkpoint ID:', False);

  if True then
  begin
    InstallLocation := GetUninstallInstallLocation();
    if InstallLocation <> '' then
    begin
      ExistingConfigPath := InstallLocation + '\bridge.config.json';
      if ReadExistingIdentity(ExistingConfigPath, ExistingCheckpointId, ExistingBridgeId) then
        SkipCheckpointPage := True;
    end;
  end;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if PageID = CheckpointPage.ID then
    Result := SkipCheckpointPage;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ParsedId: Integer;
begin
  Result := True;

  if CurPageID = CheckpointPage.ID then
  begin
    if not TryParseCheckpointInput(CheckpointPage.Values[0], ParsedId) then
    begin
      MsgBox('Checkpoint ID must be a whole number between 1 and 999.', mbError, MB_OK);
      Result := False;
      Exit;
    end;

    EnteredCheckpointId := ParsedId;
  end;
end;

procedure WriteBridgeConfig(const ConfigPath: String; CheckpointId: Integer; const BridgeId: String);
var
  JsonText: String;
begin
  JsonText := BuildBridgeConfigJson(CheckpointId, BridgeId);
  if SaveStringToFile(ConfigPath, JsonText, False) then
    Exit;

  RaiseException('Failed to write bridge.config.json to ' + ConfigPath);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ConfigPath: String;
  JsonText: AnsiString;
  CheckpointId: Integer;
  BridgeId: String;
  ExistingCheckpointId: Integer;
  ExistingBridgeId: String;
begin
  if CurStep <> ssPostInstall then
    Exit;

  ConfigPath := ExpandConstant('{app}\bridge.config.json');
  CheckpointId := -1;
  BridgeId := '';

  if FileExists(ConfigPath) and LoadStringFromFile(ConfigPath, JsonText) then
  begin
    ExistingCheckpointId := ExtractJsonInt(JsonText, 'CheckpointId');
    ExistingBridgeId := ExtractJsonString(JsonText, 'BridgeId');

    if HasValidIdentity(ExistingCheckpointId, ExistingBridgeId) then
    begin
      CheckpointId := ExistingCheckpointId;
      BridgeId := ExistingBridgeId;
    end;
  end;

  if not HasValidIdentity(CheckpointId, BridgeId) then
  begin
    if EnteredCheckpointId < 1 then
      RaiseException('Checkpoint ID is required but was not provided.');

    CheckpointId := EnteredCheckpointId;
    BridgeId := FormatBridgeId(CheckpointId);
  end;

  WriteBridgeConfig(ConfigPath, CheckpointId, BridgeId);
end;
